# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pycqa/flake8
    rev: '4.0.1'
    hooks:
    -   id: flake8
        stages: [push]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.942'
    hooks:
    -   id: mypy
        stages: [push]

-   repo: https://github.com/pycqa/isort
    rev: '5.10.1'
    hooks:
      - id: isort
        name: isort (python)
        stages: [push]

# https://github.com/pre-commit/pre-commit/issues/761#issuecomment-394167542
-   repo: local
    hooks:
    -   id: pytest
        name: pytest
        entry: venv/bin/pytest
        language: script
        pass_filenames: false
        # alternatively you could `types: [python]` so it only runs when python files change
        # though tests might be invalidated if you were to say change a data file
        always_run: true
        stages: [push]