name: freqtrade
channels:
  - conda-forge
# - defaults
dependencies:
  - python>=3.8,<=3.10
  - pip
  - libta-lib=0.4.0 # this is required for ta-lib from requirements.txt
  - pip:
    - -r requirements.txt
    - -e .
